# Site settings
title: Eric Moe
email: you@example.com
description: > # this means to ignore newlines until "baseurl:"
  The portfolio of Eric Moe.
baseurl:  # the subpath of your site, e.g. /blog/
url:  # the base hostname & protocol for your site
twitter_username: https://twitter.com/geomoetric
github_username:  https://github.com/geomoetric

# Owner/author information
owner:
  name: Eric Moe
  
# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  poetry:
    output: true
    permalink: /poetry/:path/

gems: [jekyll-paginate]


